# 데이터 사이언스 스쿨 1.4  패키지 소개
---

## numpy  
---

NumPy(“넘파이”) 패키지는 파이썬에서 수치 해석, 특히 선형 대수(linear algebra) 계산 기능을 제공

## scipy  
---

scipy(“사이파이”) 패키지는 고급 수학 함수, 수치적 미적분, 미분 방정식 계산, 최적화, 신호 처리 등에 사용하는 다양한 과학 기술 계산 기능을 제공

## sympy  
---

SymPy(“심파이”) 패키지는 숫자를 더하거나 빼는 수치 연산이 아니라 인수 분해, 미분, 적분 등 심볼릭 연산 기능을 제공

## pandas  
---

Pandas(“판다스”) 패키지는 테이블 형태의 데이터를 다루는 데이터프레임(DataFrame) 자료형을 제공

## matplotlib  
---

Matplotlib(“맷플롯리브”) 패키지는 파이썬에서 각종 그래프나 챠트 등을 그리는 시각화 기능을 제공

## seaborn  
---

Seaborn(“시본”) 패키지는 Matplotlib 패키지에서 지원하지 않는 고급 통계 차트를 그리는 통계용 시각화 기능을 제공

# 데이터 사이언스 스쿨 3장 넘파이 배열 프로그래밍
---

## 3.1넘파이 배열  
---

많은 숫자 데이터를 하나의 변수에 넣고 관리 할 때 리스트는 속도가 느리고 메모리를 많이 차지하는 단점이 있다.   
배열(array)을 사용하면 적은 메모리로 많은 데이터를 빠르게 처리할 수 있다. 배열은 리스트와 비슷하지만 다음과 같은 점에서 다르다.

- 모든 원소가 같은 자료형이어야 한다.  
- 원소의 갯수를 바꿀 수 없다.

파이썬에서 배열을 사용하기 위한 표준 패키지는 넘파이(numpy)다.

In [3]:
import numpy as np

### 1차원 배열 만들기  
---

In [4]:
ar = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
type(ar)

numpy.ndarray

ndarray 객체의 표현식(representation)을 보면 바깥쪽에 array()란 것이 붙어 있을 뿐 리스트와 동일한 구조처럼 보인다. 그러나 배열 객체와 리스트 객체는 많은 차이가 있다.리스트 클래스 객체는 각각의 원소가 다른 자료형이 될 수 있다. 그러나 배열 객체 객체는 C언어의 배열처럼 연속적인 메모리 배치를 가지기 때문에 모든 원소가 같은 자료형이어야 한다. 

### 벡터화 연산  
---

리스트는 for문으로 계산

In [6]:
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
answer = []
for di in data:
    answer.append(2 * di)
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

배열을 사용하면 편해짐

In [8]:
x = np.array(data)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
2 * x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [11]:
2 * a + b

array([12, 24, 36])

In [12]:
(a == 2) & (b > 10)

array([False,  True, False])

### 2차원 배열 만들기  
---

In [13]:
c = np.array([[0, 1, 2], [3, 4, 5]])  # 2 x 3 array
c

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
# 행의 갯수
len(c)

2

In [15]:
# 열의 갯수
len(c[0])

3

### 3차원 배열 만들기  
---

In [16]:
d = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]])   # 2 x 3 x 4 array

In [18]:
len(d), len(d[0]), len(d[0][0]) #깊이,행,열

(2, 3, 4)

### 배열의 차원과 크기 알아내기

In [19]:
a = np.array([1, 2, 3])
print(a.ndim)
print(a.shape)

1
(3,)


 ndim 속성은 배열의 차원, shape 속성은 배열의 크기를 반환

In [21]:
print(d.ndim)
print(d.shape)

3
(2, 3, 4)


### 배열의 인덱싱

In [22]:
a = np.array([0, 1, 2, 3, 4])
a[2]

2

In [23]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a[0, 1]  # 첫번째 행의 두번째 열

1

### 배열 슬라이싱